architectury {
    common(rootProject.enabled_platforms.split(","))
}

loom {
    accessWidenerPath = file("src/main/resources/tinymobfarm.accesswidener")
}

dependencies {
    // Remove the next line if you don't want to depend on the API
    modApi "dev.architectury:architectury:${project.architectury_version}"

    modCompileOnly "curse.maven:yaml-config-1128669:${project.config_library_file_neoforge}"
    modCompileOnly "curse.maven:ui-933200:${project.ui_library_file_neoforge}"
}
