modLoader = "javafml"
loaderVersion = "[4,)"
license = "Apache-2.0"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = "${mod_description}"
#logoFile = ""

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "yamlconfig"
type = "required"
versionRange = "[${config_library_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "uilib"
type = "required"
versionRange = "[${ui_library_version},)"
ordering = "AFTER"
side = "CLIENT"

